### ISSUE TITLE
Automatic roadblock blocks the "on duty" loading

### ISSUE THREAD

**Issue by Ninovui** [yoep/AutomaticRoadblock#156] opened 2023-10-13 09:27 UTC
I've been trying to update the plugin, but from now on, I can't load on"ForceDuty" or the usual way. I'm just in an infinite loading and nothing happen.
[RagePluginHook.log](https://github.com/yoep/AutomaticRoadblock/files/12891948/RagePluginHook.log)

**Comment by yoep** [comment] 2023-10-13 16:13
Hi,

Could you set the `Logging` key in the `AutomaticRoadblocks.ini` file to `Trace` and resend me the log file after loading?
As I'm currently unable to determine the exact subprocess in which the OnDuty hangs.

**Comment by yoep** [comment] 2023-10-13 17:46
On the other hand, I might have just found the underlying issue.

It seems that on some computers, the loading of the scenery items in memory gets stuck for some reason.
So I've moved the asset loading to async threads in the hope that this will fix the issue.

Expect a patch to be released soon for testing purpose.

**Comment by Ninovui** [comment] 2023-10-13 22:41
Hey. Here's the log as requested. Enjoy :)
[RagePluginHook.log](https://github.com/yoep/AutomaticRoadblock/files/12900005/RagePluginHook.log)

**Comment by yoep** [comment] 2023-10-15 08:30
Confirmed by [Christian046](https://www.lcpdfr.com/profile/492968-christian046/) that the issue is fixed in 0.7.4

**Closed by yoep** 2023-10-15 08:30 UTC
Labels: bug
